TravisCI: fix OSX builds
Summary:
Apparently, `brew install` fails if the package is already installed?
```
Error: automake 1.15 is already installed
```
https://travis-ci.org/caffe2/caffe2/jobs/245226634

Maybe TravisCI made some unannounced updates to their OSX images at around the same time [they updated their trusty images](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch). Something changed on their side two days ago, and the OSX builds have been failing ever since.
Closes https://github.com/caffe2/caffe2/pull/858

Differential Revision: D5313447

Pulled By: aaronmarkham

fbshipit-source-id: 7085640704c60c0119a1a75ea69dacd64b5a4da8