fix #985 compilation error due to type mismatch
Summary:
Fix the error during compilation on Win10+CUDA, not sure if it affects Linux and MacOS.
caffe2/operators/top_k_radix_selection.cuh(359): error : a value of type "caffe2::TIndex *" cannot be used to initialize an entity of type "long *"
Closes https://github.com/caffe2/caffe2/pull/992

Differential Revision: D5532399

Pulled By: Yangqing

fbshipit-source-id: 6958ee4f21053f73a0628cf98936931099211749